import type { OutageReport } from "@/types/outage";
import { Timestamp } from "firebase/firestore";

export const mockOutages: OutageReport[] = [
  {
    id: "mock-1",
    lat: 18.4655,
    lng: -66.1057,
    outageType: "power",
    createdAt: Timestamp.fromDate(new Date(Date.now() - 1000 * 60 * 10)),
    confirmations: 5,
    hasServiceNearby: false,
    weatherCondition: "storm",
    reporterEmail: "maria.torres@email.com",
    reporterMobileNumber: "+1 (787) 555-1234",
  },
  {
    id: "mock-2",
    lat: 18.0111,
    lng: -66.6141,
    outageType: "water",
    createdAt: Timestamp.fromDate(new Date(Date.now() - 1000 * 60 * 25)),
    confirmations: 2,
    hasServiceNearby: true,
    weatherCondition: "rain",
  },
  {
    id: "mock-3",
    lat: 18.2011,
    lng: -67.1396,
    outageType: "power",
    createdAt: Timestamp.fromDate(new Date(Date.now() - 1000 * 60 * 5)),
    confirmations: 8,
    hasServiceNearby: false,
    weatherCondition: "wind",
    reporterEmail: "juan.lopez@email.com",
  },
  {
    id: "mock-4",
    lat: 18.3808,
    lng: -65.9574,
    outageType: "water",
    createdAt: Timestamp.fromDate(new Date(Date.now() - 1000 * 60 * 45)),
    confirmations: 1,
    hasServiceNearby: false,
    weatherCondition: "clear",
    reporterMobileNumber: "+1 (787) 555-5678",
  },
  {
    id: "mock-5",
    lat: 18.3358,
    lng: -64.8963,
    outageType: "power",
    createdAt: Timestamp.fromDate(new Date(Date.now() - 1000 * 60 * 60)),
    confirmations: 12,
    hasServiceNearby: true,
    weatherCondition: "other",
    reporterEmail: "carlos.rivera@email.com",
    reporterMobileNumber: "+1 (787) 555-9012",
  },
];
